// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.0
// source: lsp/weibo/weibo.proto

package weibo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardType int32

const (
	CardType_Unknown CardType = 0
	// 发文字，图文，都是9
	CardType_Normal CardType = 9
)

// Enum value maps for CardType.
var (
	CardType_name = map[int32]string{
		0: "Unknown",
		9: "Normal",
	}
	CardType_value = map[string]int32{
		"Unknown": 0,
		"Normal":  9,
	}
)

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}

func (x CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_lsp_weibo_weibo_proto_enumTypes[0].Descriptor()
}

func (CardType) Type() protoreflect.EnumType {
	return &file_lsp_weibo_weibo_proto_enumTypes[0]
}

func (x CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardType.Descriptor instead.
func (CardType) EnumDescriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{0}
}

type GenVisitorResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Retcode       int64                    `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Msg           string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *GenVisitorResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenVisitorResponse) Reset() {
	*x = GenVisitorResponse{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenVisitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenVisitorResponse) ProtoMessage() {}

func (x *GenVisitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenVisitorResponse.ProtoReflect.Descriptor instead.
func (*GenVisitorResponse) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{0}
}

func (x *GenVisitorResponse) GetRetcode() int64 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GenVisitorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GenVisitorResponse) GetData() *GenVisitorResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type VisitorIncarnateResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Retcode       int64                          `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Msg           string                         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *VisitorIncarnateResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorIncarnateResponse) Reset() {
	*x = VisitorIncarnateResponse{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorIncarnateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorIncarnateResponse) ProtoMessage() {}

func (x *VisitorIncarnateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorIncarnateResponse.ProtoReflect.Descriptor instead.
func (*VisitorIncarnateResponse) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{1}
}

func (x *VisitorIncarnateResponse) GetRetcode() int64 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *VisitorIncarnateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *VisitorIncarnateResponse) GetData() *VisitorIncarnateResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiContainerGetIndexProfileResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Ok            int32                                     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                                    `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ApiContainerGetIndexProfileResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiContainerGetIndexProfileResponse) Reset() {
	*x = ApiContainerGetIndexProfileResponse{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiContainerGetIndexProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexProfileResponse) ProtoMessage() {}

func (x *ApiContainerGetIndexProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexProfileResponse.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexProfileResponse) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{2}
}

func (x *ApiContainerGetIndexProfileResponse) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *ApiContainerGetIndexProfileResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApiContainerGetIndexProfileResponse) GetData() *ApiContainerGetIndexProfileResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiContainerGetIndexCardsResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Ok            int32                                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                                  `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *ApiContainerGetIndexCardsResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiContainerGetIndexCardsResponse) Reset() {
	*x = ApiContainerGetIndexCardsResponse{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiContainerGetIndexCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexCardsResponse) ProtoMessage() {}

func (x *ApiContainerGetIndexCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexCardsResponse.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexCardsResponse) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{3}
}

func (x *ApiContainerGetIndexCardsResponse) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *ApiContainerGetIndexCardsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApiContainerGetIndexCardsResponse) GetData() *ApiContainerGetIndexCardsResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Card struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CardType CardType               `protobuf:"varint,1,opt,name=card_type,json=cardType,proto3,enum=weibo.CardType" json:"card_type,omitempty"`
	ItemId   string                 `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	// 这个好像可以用来当做传送门链接
	Scheme        string      `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Mblog         *Card_Mblog `protobuf:"bytes,4,opt,name=mblog,proto3" json:"mblog,omitempty"`
	LastWeiboCard bool        `protobuf:"varint,5,opt,name=lastWeiboCard,proto3" json:"lastWeiboCard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4}
}

func (x *Card) GetCardType() CardType {
	if x != nil {
		return x.CardType
	}
	return CardType_Unknown
}

func (x *Card) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Card) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Card) GetMblog() *Card_Mblog {
	if x != nil {
		return x.Mblog
	}
	return nil
}

func (x *Card) GetLastWeiboCard() bool {
	if x != nil {
		return x.LastWeiboCard
	}
	return false
}

type GenVisitorResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           string                 `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	NewTid        bool                   `protobuf:"varint,2,opt,name=new_tid,json=newTid,proto3" json:"new_tid,omitempty"`
	Confidence    int32                  `protobuf:"varint,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenVisitorResponse_Data) Reset() {
	*x = GenVisitorResponse_Data{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenVisitorResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenVisitorResponse_Data) ProtoMessage() {}

func (x *GenVisitorResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenVisitorResponse_Data.ProtoReflect.Descriptor instead.
func (*GenVisitorResponse_Data) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GenVisitorResponse_Data) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *GenVisitorResponse_Data) GetNewTid() bool {
	if x != nil {
		return x.NewTid
	}
	return false
}

func (x *GenVisitorResponse_Data) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type VisitorIncarnateResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sub           string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Subp          string                 `protobuf:"bytes,2,opt,name=subp,proto3" json:"subp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitorIncarnateResponse_Data) Reset() {
	*x = VisitorIncarnateResponse_Data{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitorIncarnateResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitorIncarnateResponse_Data) ProtoMessage() {}

func (x *VisitorIncarnateResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitorIncarnateResponse_Data.ProtoReflect.Descriptor instead.
func (*VisitorIncarnateResponse_Data) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{1, 0}
}

func (x *VisitorIncarnateResponse_Data) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *VisitorIncarnateResponse_Data) GetSubp() string {
	if x != nil {
		return x.Subp
	}
	return ""
}

type ApiContainerGetIndexProfileResponse_Data struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	UserInfo      *ApiContainerGetIndexProfileResponse_Data_UserInfo `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiContainerGetIndexProfileResponse_Data) Reset() {
	*x = ApiContainerGetIndexProfileResponse_Data{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiContainerGetIndexProfileResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexProfileResponse_Data) ProtoMessage() {}

func (x *ApiContainerGetIndexProfileResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexProfileResponse_Data.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexProfileResponse_Data) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ApiContainerGetIndexProfileResponse_Data) GetUserInfo() *ApiContainerGetIndexProfileResponse_Data_UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type ApiContainerGetIndexProfileResponse_Data_UserInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ScreenName      string                 `protobuf:"bytes,2,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,3,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	ProfileUrl      string                 `protobuf:"bytes,4,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) Reset() {
	*x = ApiContainerGetIndexProfileResponse_Data_UserInfo{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexProfileResponse_Data_UserInfo) ProtoMessage() {}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexProfileResponse_Data_UserInfo.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexProfileResponse_Data_UserInfo) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetScreenName() string {
	if x != nil {
		return x.ScreenName
	}
	return ""
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *ApiContainerGetIndexProfileResponse_Data_UserInfo) GetProfileUrl() string {
	if x != nil {
		return x.ProfileUrl
	}
	return ""
}

type ApiContainerGetIndexCardsResponse_Data struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	CardlistInfo  *ApiContainerGetIndexCardsResponse_Data_CardListInfo `protobuf:"bytes,1,opt,name=cardlistInfo,proto3" json:"cardlistInfo,omitempty"`
	Cards         []*Card                                              `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiContainerGetIndexCardsResponse_Data) Reset() {
	*x = ApiContainerGetIndexCardsResponse_Data{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiContainerGetIndexCardsResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexCardsResponse_Data) ProtoMessage() {}

func (x *ApiContainerGetIndexCardsResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexCardsResponse_Data.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexCardsResponse_Data) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ApiContainerGetIndexCardsResponse_Data) GetCardlistInfo() *ApiContainerGetIndexCardsResponse_Data_CardListInfo {
	if x != nil {
		return x.CardlistInfo
	}
	return nil
}

func (x *ApiContainerGetIndexCardsResponse_Data) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ApiContainerGetIndexCardsResponse_Data_CardListInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containerid   string                 `protobuf:"bytes,1,opt,name=containerid,proto3" json:"containerid,omitempty"`
	VP            int32                  `protobuf:"varint,2,opt,name=v_p,json=vP,proto3" json:"v_p,omitempty"`
	ShowStyle     int32                  `protobuf:"varint,3,opt,name=show_style,json=showStyle,proto3" json:"show_style,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) Reset() {
	*x = ApiContainerGetIndexCardsResponse_Data_CardListInfo{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiContainerGetIndexCardsResponse_Data_CardListInfo) ProtoMessage() {}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiContainerGetIndexCardsResponse_Data_CardListInfo.ProtoReflect.Descriptor instead.
func (*ApiContainerGetIndexCardsResponse_Data_CardListInfo) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetContainerid() string {
	if x != nil {
		return x.Containerid
	}
	return ""
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetVP() int32 {
	if x != nil {
		return x.VP
	}
	return 0
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetShowStyle() int32 {
	if x != nil {
		return x.ShowStyle
	}
	return 0
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ApiContainerGetIndexCardsResponse_Data_CardListInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Card_Mblog struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Visible *Card_Mblog_Visible    `protobuf:"bytes,1,opt,name=visible,proto3" json:"visible,omitempty"`
	// 可以用 time.RubyDate 解析
	CreatedAt       string                                             `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Id              string                                             `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Mid             string                                             `protobuf:"bytes,4,opt,name=mid,proto3" json:"mid,omitempty"`
	Text            string                                             `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	TextLength      int32                                              `protobuf:"varint,6,opt,name=textLength,proto3" json:"textLength,omitempty"`
	PicIds          []string                                           `protobuf:"bytes,7,rep,name=pic_ids,json=picIds,proto3" json:"pic_ids,omitempty"`
	User            *ApiContainerGetIndexProfileResponse_Data_UserInfo `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	Pics            []*Card_Mblog_Pics                                 `protobuf:"bytes,9,rep,name=pics,proto3" json:"pics,omitempty"`
	IsTop           int32                                              `protobuf:"varint,10,opt,name=isTop,proto3" json:"isTop,omitempty"`
	RetweetedStatus *Card_Mblog                                        `protobuf:"bytes,11,opt,name=retweeted_status,json=retweetedStatus,proto3" json:"retweeted_status,omitempty"`
	RawText         string                                             `protobuf:"bytes,12,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	Bid             string                                             `protobuf:"bytes,13,opt,name=bid,proto3" json:"bid,omitempty"`
	PageInfo        *Card_Mblog_PageInfo                               `protobuf:"bytes,14,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Card_Mblog) Reset() {
	*x = Card_Mblog{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card_Mblog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog) ProtoMessage() {}

func (x *Card_Mblog) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog.ProtoReflect.Descriptor instead.
func (*Card_Mblog) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Card_Mblog) GetVisible() *Card_Mblog_Visible {
	if x != nil {
		return x.Visible
	}
	return nil
}

func (x *Card_Mblog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Card_Mblog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card_Mblog) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *Card_Mblog) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Card_Mblog) GetTextLength() int32 {
	if x != nil {
		return x.TextLength
	}
	return 0
}

func (x *Card_Mblog) GetPicIds() []string {
	if x != nil {
		return x.PicIds
	}
	return nil
}

func (x *Card_Mblog) GetUser() *ApiContainerGetIndexProfileResponse_Data_UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Card_Mblog) GetPics() []*Card_Mblog_Pics {
	if x != nil {
		return x.Pics
	}
	return nil
}

func (x *Card_Mblog) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *Card_Mblog) GetRetweetedStatus() *Card_Mblog {
	if x != nil {
		return x.RetweetedStatus
	}
	return nil
}

func (x *Card_Mblog) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *Card_Mblog) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *Card_Mblog) GetPageInfo() *Card_Mblog_PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type Card_Mblog_Visible struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int64                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ListId        int64                  `protobuf:"varint,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card_Mblog_Visible) Reset() {
	*x = Card_Mblog_Visible{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card_Mblog_Visible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_Visible) ProtoMessage() {}

func (x *Card_Mblog_Visible) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_Visible.ProtoReflect.Descriptor instead.
func (*Card_Mblog_Visible) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *Card_Mblog_Visible) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Card_Mblog_Visible) GetListId() int64 {
	if x != nil {
		return x.ListId
	}
	return 0
}

type Card_Mblog_Pics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Large         *Card_Mblog_Pics_Large `protobuf:"bytes,5,opt,name=large,proto3" json:"large,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	VideoSrc      string                 `protobuf:"bytes,7,opt,name=videoSrc,proto3" json:"videoSrc,omitempty"`
	Duration      float32                `protobuf:"fixed32,8,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card_Mblog_Pics) Reset() {
	*x = Card_Mblog_Pics{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card_Mblog_Pics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_Pics) ProtoMessage() {}

func (x *Card_Mblog_Pics) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_Pics.ProtoReflect.Descriptor instead.
func (*Card_Mblog_Pics) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *Card_Mblog_Pics) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *Card_Mblog_Pics) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Card_Mblog_Pics) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Card_Mblog_Pics) GetLarge() *Card_Mblog_Pics_Large {
	if x != nil {
		return x.Large
	}
	return nil
}

func (x *Card_Mblog_Pics) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Card_Mblog_Pics) GetVideoSrc() string {
	if x != nil {
		return x.VideoSrc
	}
	return ""
}

func (x *Card_Mblog_Pics) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Card_Mblog_PageInfo struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Type             string                         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	UrlOri           string                         `protobuf:"bytes,2,opt,name=url_ori,json=urlOri,proto3" json:"url_ori,omitempty"`
	PagePic          *Card_Mblog_PageInfo_PagePic   `protobuf:"bytes,3,opt,name=page_pic,json=pagePic,proto3" json:"page_pic,omitempty"`
	MediaInfo        *Card_Mblog_PageInfo_MediaInfo `protobuf:"bytes,4,opt,name=media_info,json=mediaInfo,proto3" json:"media_info,omitempty"`
	PageTitle        string                         `protobuf:"bytes,5,opt,name=page_title,json=pageTitle,proto3" json:"page_title,omitempty"`
	Title            string                         `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content1         string                         `protobuf:"bytes,7,opt,name=content1,proto3" json:"content1,omitempty"`
	Content2         string                         `protobuf:"bytes,8,opt,name=content2,proto3" json:"content2,omitempty"`
	VideoOrientation string                         `protobuf:"bytes,9,opt,name=video_orientation,json=videoOrientation,proto3" json:"video_orientation,omitempty"`
	PlayCount        string                         `protobuf:"bytes,10,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Card_Mblog_PageInfo) Reset() {
	*x = Card_Mblog_PageInfo{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card_Mblog_PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_PageInfo) ProtoMessage() {}

func (x *Card_Mblog_PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_PageInfo.ProtoReflect.Descriptor instead.
func (*Card_Mblog_PageInfo) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 2}
}

func (x *Card_Mblog_PageInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Card_Mblog_PageInfo) GetUrlOri() string {
	if x != nil {
		return x.UrlOri
	}
	return ""
}

func (x *Card_Mblog_PageInfo) GetPagePic() *Card_Mblog_PageInfo_PagePic {
	if x != nil {
		return x.PagePic
	}
	return nil
}

func (x *Card_Mblog_PageInfo) GetMediaInfo() *Card_Mblog_PageInfo_MediaInfo {
	if x != nil {
		return x.MediaInfo
	}
	return nil
}

func (x *Card_Mblog_PageInfo) GetPageTitle() string {
	if x != nil {
		return x.PageTitle
	}
	return ""
}

func (x *Card_Mblog_PageInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Card_Mblog_PageInfo) GetContent1() string {
	if x != nil {
		return x.Content1
	}
	return ""
}

func (x *Card_Mblog_PageInfo) GetContent2() string {
	if x != nil {
		return x.Content2
	}
	return ""
}

func (x *Card_Mblog_PageInfo) GetVideoOrientation() string {
	if x != nil {
		return x.VideoOrientation
	}
	return ""
}

func (x *Card_Mblog_PageInfo) GetPlayCount() string {
	if x != nil {
		return x.PlayCount
	}
	return ""
}

type Card_Mblog_Pics_Large struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          string                 `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card_Mblog_Pics_Large) Reset() {
	*x = Card_Mblog_Pics_Large{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card_Mblog_Pics_Large) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_Pics_Large) ProtoMessage() {}

func (x *Card_Mblog_Pics_Large) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_Pics_Large.ProtoReflect.Descriptor instead.
func (*Card_Mblog_Pics_Large) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 1, 0}
}

func (x *Card_Mblog_Pics_Large) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Card_Mblog_Pics_Large) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Card_Mblog_PageInfo_PagePic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	IsSelfCover   string                 `protobuf:"bytes,2,opt,name=is_self_cover,json=isSelfCover,proto3" json:"is_self_cover,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card_Mblog_PageInfo_PagePic) Reset() {
	*x = Card_Mblog_PageInfo_PagePic{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card_Mblog_PageInfo_PagePic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_PageInfo_PagePic) ProtoMessage() {}

func (x *Card_Mblog_PageInfo_PagePic) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_PageInfo_PagePic.ProtoReflect.Descriptor instead.
func (*Card_Mblog_PageInfo_PagePic) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 2, 0}
}

func (x *Card_Mblog_PageInfo_PagePic) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Card_Mblog_PageInfo_PagePic) GetIsSelfCover() string {
	if x != nil {
		return x.IsSelfCover
	}
	return ""
}

func (x *Card_Mblog_PageInfo_PagePic) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Card_Mblog_PageInfo_PagePic) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Card_Mblog_PageInfo_MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	StreamUrlHd   string                 `protobuf:"bytes,2,opt,name=stream_url_hd,json=streamUrlHd,proto3" json:"stream_url_hd,omitempty"`
	Duration      float32                `protobuf:"fixed32,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card_Mblog_PageInfo_MediaInfo) Reset() {
	*x = Card_Mblog_PageInfo_MediaInfo{}
	mi := &file_lsp_weibo_weibo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card_Mblog_PageInfo_MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card_Mblog_PageInfo_MediaInfo) ProtoMessage() {}

func (x *Card_Mblog_PageInfo_MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_weibo_weibo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card_Mblog_PageInfo_MediaInfo.ProtoReflect.Descriptor instead.
func (*Card_Mblog_PageInfo_MediaInfo) Descriptor() ([]byte, []int) {
	return file_lsp_weibo_weibo_proto_rawDescGZIP(), []int{4, 0, 2, 1}
}

func (x *Card_Mblog_PageInfo_MediaInfo) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *Card_Mblog_PageInfo_MediaInfo) GetStreamUrlHd() string {
	if x != nil {
		return x.StreamUrlHd
	}
	return ""
}

func (x *Card_Mblog_PageInfo_MediaInfo) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_lsp_weibo_weibo_proto protoreflect.FileDescriptor

const file_lsp_weibo_weibo_proto_rawDesc = "" +
	"\n" +
	"\x15lsp/weibo/weibo.proto\x12\x05weibo\"\xc7\x01\n" +
	"\x12GenVisitorResponse\x12\x18\n" +
	"\aretcode\x18\x01 \x01(\x03R\aretcode\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x1e.weibo.GenVisitorResponse.DataR\x04data\x1aQ\n" +
	"\x04Data\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\tR\x03tid\x12\x17\n" +
	"\anew_tid\x18\x02 \x01(\bR\x06newTid\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x05R\n" +
	"confidence\"\xae\x01\n" +
	"\x18VisitorIncarnateResponse\x12\x18\n" +
	"\aretcode\x18\x01 \x01(\x03R\aretcode\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x128\n" +
	"\x04data\x18\x03 \x01(\v2$.weibo.VisitorIncarnateResponse.DataR\x04data\x1a,\n" +
	"\x04Data\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x12\n" +
	"\x04subp\x18\x02 \x01(\tR\x04subp\"\xf6\x02\n" +
	"#ApiContainerGetIndexProfileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\x05R\x02ok\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12C\n" +
	"\x04data\x18\x02 \x01(\v2/.weibo.ApiContainerGetIndexProfileResponse.DataR\x04data\x1a\xe7\x01\n" +
	"\x04Data\x12T\n" +
	"\buserInfo\x18\x01 \x01(\v28.weibo.ApiContainerGetIndexProfileResponse.Data.UserInfoR\buserInfo\x1a\x88\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vscreen_name\x18\x02 \x01(\tR\n" +
	"screenName\x12*\n" +
	"\x11profile_image_url\x18\x03 \x01(\tR\x0fprofileImageUrl\x12\x1f\n" +
	"\vprofile_url\x18\x04 \x01(\tR\n" +
	"profileUrl\"\xa1\x03\n" +
	"!ApiContainerGetIndexCardsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\x05R\x02ok\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12A\n" +
	"\x04data\x18\x02 \x01(\v2-.weibo.ApiContainerGetIndexCardsResponse.DataR\x04data\x1a\x96\x02\n" +
	"\x04Data\x12^\n" +
	"\fcardlistInfo\x18\x01 \x01(\v2:.weibo.ApiContainerGetIndexCardsResponse.Data.CardListInfoR\fcardlistInfo\x12!\n" +
	"\x05cards\x18\x02 \x03(\v2\v.weibo.CardR\x05cards\x1a\x8a\x01\n" +
	"\fCardListInfo\x12 \n" +
	"\vcontainerid\x18\x01 \x01(\tR\vcontainerid\x12\x0f\n" +
	"\x03v_p\x18\x02 \x01(\x05R\x02vP\x12\x1d\n" +
	"\n" +
	"show_style\x18\x03 \x01(\x05R\tshowStyle\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\"\xac\f\n" +
	"\x04Card\x12,\n" +
	"\tcard_type\x18\x01 \x01(\x0e2\x0f.weibo.CardTypeR\bcardType\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\tR\x06itemId\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x12'\n" +
	"\x05mblog\x18\x04 \x01(\v2\x11.weibo.Card.MblogR\x05mblog\x12$\n" +
	"\rlastWeiboCard\x18\x05 \x01(\bR\rlastWeiboCard\x1a\xf6\n" +
	"\n" +
	"\x05Mblog\x123\n" +
	"\avisible\x18\x01 \x01(\v2\x19.weibo.Card.Mblog.VisibleR\avisible\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x10\n" +
	"\x03mid\x18\x04 \x01(\tR\x03mid\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"textLength\x18\x06 \x01(\x05R\n" +
	"textLength\x12\x17\n" +
	"\apic_ids\x18\a \x03(\tR\x06picIds\x12L\n" +
	"\x04user\x18\b \x01(\v28.weibo.ApiContainerGetIndexProfileResponse.Data.UserInfoR\x04user\x12*\n" +
	"\x04pics\x18\t \x03(\v2\x16.weibo.Card.Mblog.PicsR\x04pics\x12\x14\n" +
	"\x05isTop\x18\n" +
	" \x01(\x05R\x05isTop\x12<\n" +
	"\x10retweeted_status\x18\v \x01(\v2\x11.weibo.Card.MblogR\x0fretweetedStatus\x12\x19\n" +
	"\braw_text\x18\f \x01(\tR\arawText\x12\x10\n" +
	"\x03bid\x18\r \x01(\tR\x03bid\x127\n" +
	"\tpage_info\x18\x0e \x01(\v2\x1a.weibo.Card.Mblog.PageInfoR\bpageInfo\x1a6\n" +
	"\aVisible\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x03R\x04type\x12\x17\n" +
	"\alist_id\x18\x02 \x01(\x03R\x06listId\x1a\xed\x01\n" +
	"\x04Pics\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\x122\n" +
	"\x05large\x18\x05 \x01(\v2\x1c.weibo.Card.Mblog.Pics.LargeR\x05large\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1a\n" +
	"\bvideoSrc\x18\a \x01(\tR\bvideoSrc\x12\x1a\n" +
	"\bduration\x18\b \x01(\x02R\bduration\x1a-\n" +
	"\x05Large\x12\x12\n" +
	"\x04size\x18\x01 \x01(\tR\x04size\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x1a\xcd\x04\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\aurl_ori\x18\x02 \x01(\tR\x06urlOri\x12=\n" +
	"\bpage_pic\x18\x03 \x01(\v2\".weibo.Card.Mblog.PageInfo.PagePicR\apagePic\x12C\n" +
	"\n" +
	"media_info\x18\x04 \x01(\v2$.weibo.Card.Mblog.PageInfo.MediaInfoR\tmediaInfo\x12\x1d\n" +
	"\n" +
	"page_title\x18\x05 \x01(\tR\tpageTitle\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1a\n" +
	"\bcontent1\x18\a \x01(\tR\bcontent1\x12\x1a\n" +
	"\bcontent2\x18\b \x01(\tR\bcontent2\x12+\n" +
	"\x11video_orientation\x18\t \x01(\tR\x10videoOrientation\x12\x1d\n" +
	"\n" +
	"play_count\x18\n" +
	" \x01(\tR\tplayCount\x1ak\n" +
	"\aPagePic\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\"\n" +
	"\ris_self_cover\x18\x02 \x01(\tR\visSelfCover\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x1aj\n" +
	"\tMediaInfo\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\x12\"\n" +
	"\rstream_url_hd\x18\x02 \x01(\tR\vstreamUrlHd\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x02R\bduration*#\n" +
	"\bCardType\x12\v\n" +
	"\aUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06Normal\x10\tB\vZ\tlsp/weibob\x06proto3"

var (
	file_lsp_weibo_weibo_proto_rawDescOnce sync.Once
	file_lsp_weibo_weibo_proto_rawDescData []byte
)

func file_lsp_weibo_weibo_proto_rawDescGZIP() []byte {
	file_lsp_weibo_weibo_proto_rawDescOnce.Do(func() {
		file_lsp_weibo_weibo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lsp_weibo_weibo_proto_rawDesc), len(file_lsp_weibo_weibo_proto_rawDesc)))
	})
	return file_lsp_weibo_weibo_proto_rawDescData
}

var file_lsp_weibo_weibo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lsp_weibo_weibo_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_lsp_weibo_weibo_proto_goTypes = []any{
	(CardType)(0),                                               // 0: weibo.CardType
	(*GenVisitorResponse)(nil),                                  // 1: weibo.GenVisitorResponse
	(*VisitorIncarnateResponse)(nil),                            // 2: weibo.VisitorIncarnateResponse
	(*ApiContainerGetIndexProfileResponse)(nil),                 // 3: weibo.ApiContainerGetIndexProfileResponse
	(*ApiContainerGetIndexCardsResponse)(nil),                   // 4: weibo.ApiContainerGetIndexCardsResponse
	(*Card)(nil),                                                // 5: weibo.Card
	(*GenVisitorResponse_Data)(nil),                             // 6: weibo.GenVisitorResponse.Data
	(*VisitorIncarnateResponse_Data)(nil),                       // 7: weibo.VisitorIncarnateResponse.Data
	(*ApiContainerGetIndexProfileResponse_Data)(nil),            // 8: weibo.ApiContainerGetIndexProfileResponse.Data
	(*ApiContainerGetIndexProfileResponse_Data_UserInfo)(nil),   // 9: weibo.ApiContainerGetIndexProfileResponse.Data.UserInfo
	(*ApiContainerGetIndexCardsResponse_Data)(nil),              // 10: weibo.ApiContainerGetIndexCardsResponse.Data
	(*ApiContainerGetIndexCardsResponse_Data_CardListInfo)(nil), // 11: weibo.ApiContainerGetIndexCardsResponse.Data.CardListInfo
	(*Card_Mblog)(nil),                                          // 12: weibo.Card.Mblog
	(*Card_Mblog_Visible)(nil),                                  // 13: weibo.Card.Mblog.Visible
	(*Card_Mblog_Pics)(nil),                                     // 14: weibo.Card.Mblog.Pics
	(*Card_Mblog_PageInfo)(nil),                                 // 15: weibo.Card.Mblog.PageInfo
	(*Card_Mblog_Pics_Large)(nil),                               // 16: weibo.Card.Mblog.Pics.Large
	(*Card_Mblog_PageInfo_PagePic)(nil),                         // 17: weibo.Card.Mblog.PageInfo.PagePic
	(*Card_Mblog_PageInfo_MediaInfo)(nil),                       // 18: weibo.Card.Mblog.PageInfo.MediaInfo
}
var file_lsp_weibo_weibo_proto_depIdxs = []int32{
	6,  // 0: weibo.GenVisitorResponse.data:type_name -> weibo.GenVisitorResponse.Data
	7,  // 1: weibo.VisitorIncarnateResponse.data:type_name -> weibo.VisitorIncarnateResponse.Data
	8,  // 2: weibo.ApiContainerGetIndexProfileResponse.data:type_name -> weibo.ApiContainerGetIndexProfileResponse.Data
	10, // 3: weibo.ApiContainerGetIndexCardsResponse.data:type_name -> weibo.ApiContainerGetIndexCardsResponse.Data
	0,  // 4: weibo.Card.card_type:type_name -> weibo.CardType
	12, // 5: weibo.Card.mblog:type_name -> weibo.Card.Mblog
	9,  // 6: weibo.ApiContainerGetIndexProfileResponse.Data.userInfo:type_name -> weibo.ApiContainerGetIndexProfileResponse.Data.UserInfo
	11, // 7: weibo.ApiContainerGetIndexCardsResponse.Data.cardlistInfo:type_name -> weibo.ApiContainerGetIndexCardsResponse.Data.CardListInfo
	5,  // 8: weibo.ApiContainerGetIndexCardsResponse.Data.cards:type_name -> weibo.Card
	13, // 9: weibo.Card.Mblog.visible:type_name -> weibo.Card.Mblog.Visible
	9,  // 10: weibo.Card.Mblog.user:type_name -> weibo.ApiContainerGetIndexProfileResponse.Data.UserInfo
	14, // 11: weibo.Card.Mblog.pics:type_name -> weibo.Card.Mblog.Pics
	12, // 12: weibo.Card.Mblog.retweeted_status:type_name -> weibo.Card.Mblog
	15, // 13: weibo.Card.Mblog.page_info:type_name -> weibo.Card.Mblog.PageInfo
	16, // 14: weibo.Card.Mblog.Pics.large:type_name -> weibo.Card.Mblog.Pics.Large
	17, // 15: weibo.Card.Mblog.PageInfo.page_pic:type_name -> weibo.Card.Mblog.PageInfo.PagePic
	18, // 16: weibo.Card.Mblog.PageInfo.media_info:type_name -> weibo.Card.Mblog.PageInfo.MediaInfo
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_lsp_weibo_weibo_proto_init() }
func file_lsp_weibo_weibo_proto_init() {
	if File_lsp_weibo_weibo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lsp_weibo_weibo_proto_rawDesc), len(file_lsp_weibo_weibo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lsp_weibo_weibo_proto_goTypes,
		DependencyIndexes: file_lsp_weibo_weibo_proto_depIdxs,
		EnumInfos:         file_lsp_weibo_weibo_proto_enumTypes,
		MessageInfos:      file_lsp_weibo_weibo_proto_msgTypes,
	}.Build()
	File_lsp_weibo_weibo_proto = out.File
	file_lsp_weibo_weibo_proto_goTypes = nil
	file_lsp_weibo_weibo_proto_depIdxs = nil
}
