// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.28.0
// source: lsp/douyin/douyin.proto

package douyin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 精简后的UserPostsResponse定义，只保留推送和可视化所需的关键字段
type UserPostsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	StatusCode    int32                          `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	MinCursor     int64                          `protobuf:"varint,2,opt,name=min_cursor,json=minCursor,proto3" json:"min_cursor,omitempty"`
	MaxCursor     int64                          `protobuf:"varint,3,opt,name=max_cursor,json=maxCursor,proto3" json:"max_cursor,omitempty"`
	HasMore       int32                          `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	AwemeList     []*UserPostsResponse_AwemeList `protobuf:"bytes,5,rep,name=aweme_list,json=awemeList,proto3" json:"aweme_list,omitempty"`
	LogPb         *UserPostsResponse_LogPb       `protobuf:"bytes,7,opt,name=log_pb,json=logPb,proto3" json:"log_pb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse) Reset() {
	*x = UserPostsResponse{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse) ProtoMessage() {}

func (x *UserPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse.ProtoReflect.Descriptor instead.
func (*UserPostsResponse) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0}
}

func (x *UserPostsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UserPostsResponse) GetMinCursor() int64 {
	if x != nil {
		return x.MinCursor
	}
	return 0
}

func (x *UserPostsResponse) GetMaxCursor() int64 {
	if x != nil {
		return x.MaxCursor
	}
	return 0
}

func (x *UserPostsResponse) GetHasMore() int32 {
	if x != nil {
		return x.HasMore
	}
	return 0
}

func (x *UserPostsResponse) GetAwemeList() []*UserPostsResponse_AwemeList {
	if x != nil {
		return x.AwemeList
	}
	return nil
}

func (x *UserPostsResponse) GetLogPb() *UserPostsResponse_LogPb {
	if x != nil {
		return x.LogPb
	}
	return nil
}

// 作者信息
type UserPostsResponse_Author struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Uid           string                         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                         `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarThumb   *UserPostsResponse_AvatarThumb `protobuf:"bytes,6,opt,name=avatar_thumb,json=avatarThumb,proto3" json:"avatar_thumb,omitempty"`
	SecUid        string                         `protobuf:"bytes,53,opt,name=sec_uid,json=secUid,proto3" json:"sec_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_Author) Reset() {
	*x = UserPostsResponse_Author{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_Author) ProtoMessage() {}

func (x *UserPostsResponse_Author) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_Author.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_Author) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserPostsResponse_Author) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserPostsResponse_Author) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserPostsResponse_Author) GetAvatarThumb() *UserPostsResponse_AvatarThumb {
	if x != nil {
		return x.AvatarThumb
	}
	return nil
}

func (x *UserPostsResponse_Author) GetSecUid() string {
	if x != nil {
		return x.SecUid
	}
	return ""
}

// 头像信息
type UserPostsResponse_AvatarThumb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	UrlList       []string               `protobuf:"bytes,2,rep,name=url_list,json=urlList,proto3" json:"url_list,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_AvatarThumb) Reset() {
	*x = UserPostsResponse_AvatarThumb{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_AvatarThumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_AvatarThumb) ProtoMessage() {}

func (x *UserPostsResponse_AvatarThumb) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_AvatarThumb.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_AvatarThumb) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UserPostsResponse_AvatarThumb) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UserPostsResponse_AvatarThumb) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

func (x *UserPostsResponse_AvatarThumb) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserPostsResponse_AvatarThumb) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 音乐信息
type UserPostsResponse_Music struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            int64                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdStr         string                        `protobuf:"bytes,2,opt,name=id_str,json=idStr,proto3" json:"id_str,omitempty"`
	Title         string                        `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                        `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Album         string                        `protobuf:"bytes,5,opt,name=album,proto3" json:"album,omitempty"`
	CoverThumb    *UserPostsResponse_CoverThumb `protobuf:"bytes,9,opt,name=cover_thumb,json=coverThumb,proto3" json:"cover_thumb,omitempty"`
	PlayUrl       *UserPostsResponse_PlayUrl    `protobuf:"bytes,10,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	Duration      int32                         `protobuf:"varint,15,opt,name=duration,proto3" json:"duration,omitempty"`
	OwnerNickname string                        `protobuf:"bytes,23,opt,name=owner_nickname,json=ownerNickname,proto3" json:"owner_nickname,omitempty"`
	IsOriginal    bool                          `protobuf:"varint,24,opt,name=is_original,json=isOriginal,proto3" json:"is_original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_Music) Reset() {
	*x = UserPostsResponse_Music{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_Music) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_Music) ProtoMessage() {}

func (x *UserPostsResponse_Music) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_Music.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_Music) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 2}
}

func (x *UserPostsResponse_Music) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPostsResponse_Music) GetIdStr() string {
	if x != nil {
		return x.IdStr
	}
	return ""
}

func (x *UserPostsResponse_Music) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserPostsResponse_Music) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UserPostsResponse_Music) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *UserPostsResponse_Music) GetCoverThumb() *UserPostsResponse_CoverThumb {
	if x != nil {
		return x.CoverThumb
	}
	return nil
}

func (x *UserPostsResponse_Music) GetPlayUrl() *UserPostsResponse_PlayUrl {
	if x != nil {
		return x.PlayUrl
	}
	return nil
}

func (x *UserPostsResponse_Music) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UserPostsResponse_Music) GetOwnerNickname() string {
	if x != nil {
		return x.OwnerNickname
	}
	return ""
}

func (x *UserPostsResponse_Music) GetIsOriginal() bool {
	if x != nil {
		return x.IsOriginal
	}
	return false
}

// 封面信息
type UserPostsResponse_CoverThumb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	UrlList       []string               `protobuf:"bytes,2,rep,name=url_list,json=urlList,proto3" json:"url_list,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_CoverThumb) Reset() {
	*x = UserPostsResponse_CoverThumb{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_CoverThumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_CoverThumb) ProtoMessage() {}

func (x *UserPostsResponse_CoverThumb) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_CoverThumb.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_CoverThumb) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 3}
}

func (x *UserPostsResponse_CoverThumb) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UserPostsResponse_CoverThumb) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

func (x *UserPostsResponse_CoverThumb) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserPostsResponse_CoverThumb) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 播放地址信息
type UserPostsResponse_PlayUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	UrlList       []string               `protobuf:"bytes,2,rep,name=url_list,json=urlList,proto3" json:"url_list,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	UrlKey        string                 `protobuf:"bytes,5,opt,name=url_key,json=urlKey,proto3" json:"url_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_PlayUrl) Reset() {
	*x = UserPostsResponse_PlayUrl{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_PlayUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_PlayUrl) ProtoMessage() {}

func (x *UserPostsResponse_PlayUrl) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_PlayUrl.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_PlayUrl) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 4}
}

func (x *UserPostsResponse_PlayUrl) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UserPostsResponse_PlayUrl) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

func (x *UserPostsResponse_PlayUrl) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserPostsResponse_PlayUrl) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserPostsResponse_PlayUrl) GetUrlKey() string {
	if x != nil {
		return x.UrlKey
	}
	return ""
}

// 视频信息
type UserPostsResponse_Video struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	PlayAddr      *UserPostsResponse_PlayAddr     `protobuf:"bytes,1,opt,name=play_addr,json=playAddr,proto3" json:"play_addr,omitempty"`
	Cover         *UserPostsResponse_Cover        `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	Height        int32                           `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width         int32                           `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	DynamicCover  *UserPostsResponse_DynamicCover `protobuf:"bytes,5,opt,name=dynamic_cover,json=dynamicCover,proto3" json:"dynamic_cover,omitempty"`
	OriginCover   *UserPostsResponse_OriginCover  `protobuf:"bytes,6,opt,name=origin_cover,json=originCover,proto3" json:"origin_cover,omitempty"`
	Ratio         string                          `protobuf:"bytes,7,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Duration      int32                           `protobuf:"varint,12,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_Video) Reset() {
	*x = UserPostsResponse_Video{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_Video) ProtoMessage() {}

func (x *UserPostsResponse_Video) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_Video.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_Video) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 5}
}

func (x *UserPostsResponse_Video) GetPlayAddr() *UserPostsResponse_PlayAddr {
	if x != nil {
		return x.PlayAddr
	}
	return nil
}

func (x *UserPostsResponse_Video) GetCover() *UserPostsResponse_Cover {
	if x != nil {
		return x.Cover
	}
	return nil
}

func (x *UserPostsResponse_Video) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserPostsResponse_Video) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserPostsResponse_Video) GetDynamicCover() *UserPostsResponse_DynamicCover {
	if x != nil {
		return x.DynamicCover
	}
	return nil
}

func (x *UserPostsResponse_Video) GetOriginCover() *UserPostsResponse_OriginCover {
	if x != nil {
		return x.OriginCover
	}
	return nil
}

func (x *UserPostsResponse_Video) GetRatio() string {
	if x != nil {
		return x.Ratio
	}
	return ""
}

func (x *UserPostsResponse_Video) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// 播放地址
type UserPostsResponse_PlayAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	UrlList       []string               `protobuf:"bytes,2,rep,name=url_list,json=urlList,proto3" json:"url_list,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	UrlKey        string                 `protobuf:"bytes,5,opt,name=url_key,json=urlKey,proto3" json:"url_key,omitempty"`
	DataSize      int32                  `protobuf:"varint,6,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	FileHash      string                 `protobuf:"bytes,7,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_PlayAddr) Reset() {
	*x = UserPostsResponse_PlayAddr{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_PlayAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_PlayAddr) ProtoMessage() {}

func (x *UserPostsResponse_PlayAddr) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_PlayAddr.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_PlayAddr) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 6}
}

func (x *UserPostsResponse_PlayAddr) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UserPostsResponse_PlayAddr) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

func (x *UserPostsResponse_PlayAddr) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserPostsResponse_PlayAddr) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserPostsResponse_PlayAddr) GetUrlKey() string {
	if x != nil {
		return x.UrlKey
	}
	return ""
}

func (x *UserPostsResponse_PlayAddr) GetDataSize() int32 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *UserPostsResponse_PlayAddr) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

// 封面
type UserPostsResponse_Cover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	UrlList       []string               `protobuf:"bytes,2,rep,name=url_list,json=urlList,proto3" json:"url_list,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_Cover) Reset() {
	*x = UserPostsResponse_Cover{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_Cover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_Cover) ProtoMessage() {}

func (x *UserPostsResponse_Cover) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_Cover.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_Cover) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 7}
}

func (x *UserPostsResponse_Cover) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UserPostsResponse_Cover) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

func (x *UserPostsResponse_Cover) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserPostsResponse_Cover) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 动态封面
type UserPostsResponse_DynamicCover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	UrlList       []string               `protobuf:"bytes,2,rep,name=url_list,json=urlList,proto3" json:"url_list,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_DynamicCover) Reset() {
	*x = UserPostsResponse_DynamicCover{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_DynamicCover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_DynamicCover) ProtoMessage() {}

func (x *UserPostsResponse_DynamicCover) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_DynamicCover.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_DynamicCover) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 8}
}

func (x *UserPostsResponse_DynamicCover) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UserPostsResponse_DynamicCover) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

func (x *UserPostsResponse_DynamicCover) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserPostsResponse_DynamicCover) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 原始封面
type UserPostsResponse_OriginCover struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	UrlList       []string               `protobuf:"bytes,2,rep,name=url_list,json=urlList,proto3" json:"url_list,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_OriginCover) Reset() {
	*x = UserPostsResponse_OriginCover{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_OriginCover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_OriginCover) ProtoMessage() {}

func (x *UserPostsResponse_OriginCover) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_OriginCover.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_OriginCover) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 9}
}

func (x *UserPostsResponse_OriginCover) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UserPostsResponse_OriginCover) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

func (x *UserPostsResponse_OriginCover) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UserPostsResponse_OriginCover) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 统计信息
type UserPostsResponse_Statistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentCount  int32                  `protobuf:"varint,2,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	DiggCount     int32                  `protobuf:"varint,3,opt,name=digg_count,json=diggCount,proto3" json:"digg_count,omitempty"`
	PlayCount     int32                  `protobuf:"varint,5,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	ShareCount    int32                  `protobuf:"varint,6,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	CollectCount  int32                  `protobuf:"varint,7,opt,name=collect_count,json=collectCount,proto3" json:"collect_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_Statistics) Reset() {
	*x = UserPostsResponse_Statistics{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_Statistics) ProtoMessage() {}

func (x *UserPostsResponse_Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_Statistics.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_Statistics) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 10}
}

func (x *UserPostsResponse_Statistics) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *UserPostsResponse_Statistics) GetDiggCount() int32 {
	if x != nil {
		return x.DiggCount
	}
	return 0
}

func (x *UserPostsResponse_Statistics) GetPlayCount() int32 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *UserPostsResponse_Statistics) GetShareCount() int32 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *UserPostsResponse_Statistics) GetCollectCount() int32 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

// 状态信息
type UserPostsResponse_Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDelete      bool                   `protobuf:"varint,2,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	AllowShare    bool                   `protobuf:"varint,3,opt,name=allow_share,json=allowShare,proto3" json:"allow_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_Status) Reset() {
	*x = UserPostsResponse_Status{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_Status) ProtoMessage() {}

func (x *UserPostsResponse_Status) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_Status.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_Status) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 11}
}

func (x *UserPostsResponse_Status) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

func (x *UserPostsResponse_Status) GetAllowShare() bool {
	if x != nil {
		return x.AllowShare
	}
	return false
}

// 视频作品条目
type UserPostsResponse_AwemeList struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	AwemeId       string                        `protobuf:"bytes,1,opt,name=aweme_id,json=awemeId,proto3" json:"aweme_id,omitempty"`
	Desc          string                        `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	CreateTime    int32                         `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Author        *UserPostsResponse_Author     `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Music         *UserPostsResponse_Music      `protobuf:"bytes,5,opt,name=music,proto3" json:"music,omitempty"`
	Video         *UserPostsResponse_Video      `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	ShareUrl      string                        `protobuf:"bytes,8,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	Statistics    *UserPostsResponse_Statistics `protobuf:"bytes,10,opt,name=statistics,proto3" json:"statistics,omitempty"`
	Status        *UserPostsResponse_Status     `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	IsAds         bool                          `protobuf:"varint,20,opt,name=is_ads,json=isAds,proto3" json:"is_ads,omitempty"`
	Duration      int32                         `protobuf:"varint,21,opt,name=duration,proto3" json:"duration,omitempty"`
	AwemeType     int32                         `protobuf:"varint,22,opt,name=aweme_type,json=awemeType,proto3" json:"aweme_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_AwemeList) Reset() {
	*x = UserPostsResponse_AwemeList{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_AwemeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_AwemeList) ProtoMessage() {}

func (x *UserPostsResponse_AwemeList) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_AwemeList.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_AwemeList) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 12}
}

func (x *UserPostsResponse_AwemeList) GetAwemeId() string {
	if x != nil {
		return x.AwemeId
	}
	return ""
}

func (x *UserPostsResponse_AwemeList) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UserPostsResponse_AwemeList) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserPostsResponse_AwemeList) GetAuthor() *UserPostsResponse_Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *UserPostsResponse_AwemeList) GetMusic() *UserPostsResponse_Music {
	if x != nil {
		return x.Music
	}
	return nil
}

func (x *UserPostsResponse_AwemeList) GetVideo() *UserPostsResponse_Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *UserPostsResponse_AwemeList) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *UserPostsResponse_AwemeList) GetStatistics() *UserPostsResponse_Statistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *UserPostsResponse_AwemeList) GetStatus() *UserPostsResponse_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UserPostsResponse_AwemeList) GetIsAds() bool {
	if x != nil {
		return x.IsAds
	}
	return false
}

func (x *UserPostsResponse_AwemeList) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UserPostsResponse_AwemeList) GetAwemeType() int32 {
	if x != nil {
		return x.AwemeType
	}
	return 0
}

type UserPostsResponse_LogPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImprId        string                 `protobuf:"bytes,1,opt,name=impr_id,json=imprId,proto3" json:"impr_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostsResponse_LogPb) Reset() {
	*x = UserPostsResponse_LogPb{}
	mi := &file_lsp_douyin_douyin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostsResponse_LogPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostsResponse_LogPb) ProtoMessage() {}

func (x *UserPostsResponse_LogPb) ProtoReflect() protoreflect.Message {
	mi := &file_lsp_douyin_douyin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostsResponse_LogPb.ProtoReflect.Descriptor instead.
func (*UserPostsResponse_LogPb) Descriptor() ([]byte, []int) {
	return file_lsp_douyin_douyin_proto_rawDescGZIP(), []int{0, 13}
}

func (x *UserPostsResponse_LogPb) GetImprId() string {
	if x != nil {
		return x.ImprId
	}
	return ""
}

var File_lsp_douyin_douyin_proto protoreflect.FileDescriptor

var file_lsp_douyin_douyin_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6c, 0x73, 0x70, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2f, 0x64, 0x6f, 0x75,
	0x79, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x75, 0x79, 0x69,
	0x6e, 0x22, 0xd9, 0x15, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f,
	0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x69,
	0x6e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x63,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x78,
	0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72,
	0x65, 0x12, 0x42, 0x0a, 0x0a, 0x61, 0x77, 0x65, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x41, 0x77, 0x65, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x09, 0x61, 0x77, 0x65, 0x6d,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x62, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x4c, 0x6f, 0x67, 0x50, 0x62, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x50, 0x62, 0x1a, 0x99, 0x01,
	0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64,
	0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x54, 0x68,
	0x75, 0x6d, 0x62, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x54, 0x68, 0x75, 0x6d, 0x62,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x35, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x55, 0x69, 0x64, 0x1a, 0x68, 0x0a, 0x0b, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72,
	0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x1a, 0xdb, 0x02, 0x0a, 0x05, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x69, 0x64, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x64, 0x53, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x45, 0x0a, 0x0b, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x68,
	0x75, 0x6d, 0x62, 0x52, 0x0a, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x12,
	0x3c, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x55, 0x72, 0x6c, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x5f, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x17, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18,
	0x18, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x1a, 0x67, 0x0a, 0x0a, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x69, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x7d, 0x0a, 0x07, 0x50, 0x6c,
	0x61, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x72, 0x6c, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x72, 0x6c, 0x4b, 0x65, 0x79, 0x1a, 0xf6, 0x02, 0x0a, 0x05, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x12, 0x3f, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x41, 0x64, 0x64, 0x72, 0x12, 0x35, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43,
	0x6f, 0x76, 0x65, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x4b, 0x0a, 0x0d, 0x64, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x0c, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x5f, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64,
	0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x43, 0x6f,
	0x76, 0x65, 0x72, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x76, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0xb8, 0x01, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x69, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x72,
	0x6c, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x72, 0x6c,
	0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x62, 0x0a,
	0x05, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x1a, 0x69, 0x0a, 0x0c, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x43, 0x6f, 0x76, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x68, 0x0a, 0x0b,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x19, 0x0a,
	0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0xb5, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x69,
	0x67, 0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x64, 0x69, 0x67, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61,
	0x79, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x6c, 0x61, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x46,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x53, 0x68, 0x61, 0x72, 0x65, 0x1a, 0xf2, 0x03, 0x0a, 0x09, 0x41, 0x77, 0x65, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x77, 0x65, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x77, 0x65, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x35,
	0x0a, 0x05, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x75, 0x73, 0x69, 0x63, 0x52, 0x05,
	0x6d, 0x75, 0x73, 0x69, 0x63, 0x12, 0x35, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x44, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12,
	0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f,
	0x61, 0x64, 0x73, 0x18, 0x14, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x41, 0x64, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x15, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x77, 0x65, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x16, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x61, 0x77, 0x65, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x20, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x50, 0x62, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x70, 0x72, 0x49, 0x64, 0x42, 0x0c, 0x5a,
	0x0a, 0x6c, 0x73, 0x70, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_lsp_douyin_douyin_proto_rawDescOnce sync.Once
	file_lsp_douyin_douyin_proto_rawDescData = file_lsp_douyin_douyin_proto_rawDesc
)

func file_lsp_douyin_douyin_proto_rawDescGZIP() []byte {
	file_lsp_douyin_douyin_proto_rawDescOnce.Do(func() {
		file_lsp_douyin_douyin_proto_rawDescData = protoimpl.X.CompressGZIP(file_lsp_douyin_douyin_proto_rawDescData)
	})
	return file_lsp_douyin_douyin_proto_rawDescData
}

var file_lsp_douyin_douyin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_lsp_douyin_douyin_proto_goTypes = []any{
	(*UserPostsResponse)(nil),              // 0: douyin.UserPostsResponse
	(*UserPostsResponse_Author)(nil),       // 1: douyin.UserPostsResponse.Author
	(*UserPostsResponse_AvatarThumb)(nil),  // 2: douyin.UserPostsResponse.AvatarThumb
	(*UserPostsResponse_Music)(nil),        // 3: douyin.UserPostsResponse.Music
	(*UserPostsResponse_CoverThumb)(nil),   // 4: douyin.UserPostsResponse.CoverThumb
	(*UserPostsResponse_PlayUrl)(nil),      // 5: douyin.UserPostsResponse.PlayUrl
	(*UserPostsResponse_Video)(nil),        // 6: douyin.UserPostsResponse.Video
	(*UserPostsResponse_PlayAddr)(nil),     // 7: douyin.UserPostsResponse.PlayAddr
	(*UserPostsResponse_Cover)(nil),        // 8: douyin.UserPostsResponse.Cover
	(*UserPostsResponse_DynamicCover)(nil), // 9: douyin.UserPostsResponse.DynamicCover
	(*UserPostsResponse_OriginCover)(nil),  // 10: douyin.UserPostsResponse.OriginCover
	(*UserPostsResponse_Statistics)(nil),   // 11: douyin.UserPostsResponse.Statistics
	(*UserPostsResponse_Status)(nil),       // 12: douyin.UserPostsResponse.Status
	(*UserPostsResponse_AwemeList)(nil),    // 13: douyin.UserPostsResponse.AwemeList
	(*UserPostsResponse_LogPb)(nil),        // 14: douyin.UserPostsResponse.LogPb
}
var file_lsp_douyin_douyin_proto_depIdxs = []int32{
	13, // 0: douyin.UserPostsResponse.aweme_list:type_name -> douyin.UserPostsResponse.AwemeList
	14, // 1: douyin.UserPostsResponse.log_pb:type_name -> douyin.UserPostsResponse.LogPb
	2,  // 2: douyin.UserPostsResponse.Author.avatar_thumb:type_name -> douyin.UserPostsResponse.AvatarThumb
	4,  // 3: douyin.UserPostsResponse.Music.cover_thumb:type_name -> douyin.UserPostsResponse.CoverThumb
	5,  // 4: douyin.UserPostsResponse.Music.play_url:type_name -> douyin.UserPostsResponse.PlayUrl
	7,  // 5: douyin.UserPostsResponse.Video.play_addr:type_name -> douyin.UserPostsResponse.PlayAddr
	8,  // 6: douyin.UserPostsResponse.Video.cover:type_name -> douyin.UserPostsResponse.Cover
	9,  // 7: douyin.UserPostsResponse.Video.dynamic_cover:type_name -> douyin.UserPostsResponse.DynamicCover
	10, // 8: douyin.UserPostsResponse.Video.origin_cover:type_name -> douyin.UserPostsResponse.OriginCover
	1,  // 9: douyin.UserPostsResponse.AwemeList.author:type_name -> douyin.UserPostsResponse.Author
	3,  // 10: douyin.UserPostsResponse.AwemeList.music:type_name -> douyin.UserPostsResponse.Music
	6,  // 11: douyin.UserPostsResponse.AwemeList.video:type_name -> douyin.UserPostsResponse.Video
	11, // 12: douyin.UserPostsResponse.AwemeList.statistics:type_name -> douyin.UserPostsResponse.Statistics
	12, // 13: douyin.UserPostsResponse.AwemeList.status:type_name -> douyin.UserPostsResponse.Status
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_lsp_douyin_douyin_proto_init() }
func file_lsp_douyin_douyin_proto_init() {
	if File_lsp_douyin_douyin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lsp_douyin_douyin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lsp_douyin_douyin_proto_goTypes,
		DependencyIndexes: file_lsp_douyin_douyin_proto_depIdxs,
		MessageInfos:      file_lsp_douyin_douyin_proto_msgTypes,
	}.Build()
	File_lsp_douyin_douyin_proto = out.File
	file_lsp_douyin_douyin_proto_rawDesc = nil
	file_lsp_douyin_douyin_proto_goTypes = nil
	file_lsp_douyin_douyin_proto_depIdxs = nil
}
